/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.utez.app.desktop;

import Utilerias.ConexionSQLServer;
import static com.utez.app.desktop.Constants.MYSQL;
import com.utez.app.desktop.controlador.ControlSesion;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utez.app.daos.DaoLibro;
import utez.app.model.AutorBean;
import utez.app.model.LibroBean;
import utez.app.utilidades.Biblioteca;

/**
 *
 * @author Koffo
 */
public class resultadoLibro extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    private Connection conexion;
    private DaoLibro daoLibro; 
   private ControlSesion sesion;
   private List<LibroBean> lista;
    /**
     * Creates new form resultadosUsuario
     */
    public resultadoLibro() {
        this(null);
    }
    public resultadoLibro(List<LibroBean> result) {
	    this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        conexion = new Biblioteca(MYSQL).getConection();
        
        daoLibro = new DaoLibro(conexion);
        if (result == null){
            actualizarTabla();
        }else{
		lista = result;
            actualizarTabla(result);
        }
        initComponents();
        this.setLocationRelativeTo(null);
        sesion = ControlSesion.getInstance();
        if (!sesion.isAdmin()){
            btnCambiar.setVisible(false);
            btnEliminar.setVisible(false);
        }
    }

    
    
    private void actualizarTabla(){
        
       lista =daoLibro.getActive();
             actualizarTabla(lista);
    }
    private void actualizarTabla(List<LibroBean> lista){
        modelo= new DefaultTableModel (new String[]{"ISBN","Titulo","Area","Editorial","Autores","Ejemplares", "Prestamos"},0){
            Class[] types = {Object.class, String.class, String.class, String.class, String.class, Integer.class, Integer.class};
            
            @Override
            public Class getColumnClass(int index){
                return this.types[index];
            }
            public boolean isCellEditable(int index){
                return false;
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
             for (LibroBean bean : lista) {
                 String autores = "";
                            for (AutorBean autorBean : bean.getAutores()) {
                        autores += autorBean.getNombre()+" "+autorBean.getApellido();
                    }
                    
                    Object[] arreglo                           
                            = {bean.getIsbn(),bean.getNombre(),bean.getArea().getNombre(),bean.getEditorial().getNombre(),autores, daoLibro.countEjemplares(bean), daoLibro.countPrestamos(bean)};
                 
                 modelo.addRow(arreglo);
        }
        try{tblLibros.setModel(modelo);}catch(NullPointerException e){}
    }

    public void tablaBusqueda(String busqueda){
        if (busqueda.length() < 0) {
            actualizarTabla();
        } else {
            lista = new DaoLibro(conexion).findByTitulo(busqueda);
            actualizarTabla(lista);
        }
               
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel3 = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                tblLibros = new javax.swing.JTable();
                txtDato = new javax.swing.JTextField();
                btnCambiar = new javax.swing.JButton();
                btnEliminar = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados Usuario"));

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(jTable1);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla Libro"));

                tblLibros.setAutoCreateRowSorter(true);
                tblLibros.setModel(modelo);
                jScrollPane2.setViewportView(tblLibros);

                txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                txtDatoKeyPressed(evt);
                        }
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtDatoKeyReleased(evt);
                        }
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                                txtDatoKeyTyped(evt);
                        }
                });

                btnCambiar.setText("Cambiar");
                btnCambiar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCambiarActionPerformed(evt);
                        }
                });

                btnEliminar.setText("Eliminar");
                btnEliminar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEliminarActionPerformed(evt);
                        }
                });

                jLabel1.setText("Filtrar");

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                                                .addGap(6, 6, 6))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCambiar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnEliminar)
                                                .addContainerGap())))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCambiar)
                                        .addComponent(btnEliminar)
                                        .addComponent(jLabel1))
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void txtDatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             tablaBusqueda(txtDato.getText());
         }
    }//GEN-LAST:event_txtDatoKeyPressed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
    
	LibroBean libro = lista.get(tblLibros.getSelectedRow());
	
        JFrame jf = new UDLibro(libro);
	jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
	jf.setVisible(true);
	
        this.dispose();
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(rootPane, "Seguro que desea eliminar Este registro?") == JOptionPane.OK_OPTION){
	LibroBean libro = lista.get(tblLibros.getSelectedRow());
       
        libro.setAlta(false);
        daoLibro.update(libro);
        
        actualizarTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtDatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyReleased
        // TODO add your handling code here:
        tablaBusqueda(txtDato.getText());
    }//GEN-LAST:event_txtDatoKeyReleased

    private void txtDatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
       if((car<'a' || car>'z') && (car<'A' || car>'Z')            
        && car !='á' //Minúsculas            
        && car !='é'           
        && car !='í'           
        && car !='ó'          
        && car !='ú'  
        && car !='Á' //Mayúsculas            
        && car !='É'           
        && car !='Í'           
        && car !='Ó'
        && car !='Ú'
        && car !='ñ'
        && car !='Ñ'    
        && (car!=(char)KeyEvent.VK_SPACE))
    {     
    evt.consume();  

    }
    }//GEN-LAST:event_txtDatoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultadoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultadoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultadoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultadoLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultadoLibro().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCambiar;
        private javax.swing.JButton btnEliminar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable tblLibros;
        private javax.swing.JTextField txtDato;
        // End of variables declaration//GEN-END:variables
}
